// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiKey extends pulumi.CustomResource {
    /**
     * Get an existing ApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiKeyState, opts?: pulumi.CustomResourceOptions): ApiKey {
        return new ApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/apiKey:ApiKey';

    /**
     * Returns true if the given object is an instance of ApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiKey.__pulumiType;
    }

    /**
     * Set of permissions associated with the key.
     * The possible ACLs are:
     *   - <span pulumi-lang-nodejs="`search`" pulumi-lang-dotnet="`Search`" pulumi-lang-go="`search`" pulumi-lang-python="`search`" pulumi-lang-yaml="`search`" pulumi-lang-java="`search`" pulumi-lang-hcl="`search`">`search`</span>: allowed to perform search operations.
     *   - <span pulumi-lang-nodejs="`browse`" pulumi-lang-dotnet="`Browse`" pulumi-lang-go="`browse`" pulumi-lang-python="`browse`" pulumi-lang-yaml="`browse`" pulumi-lang-java="`browse`" pulumi-lang-hcl="`browse`">`browse`</span>: allowed to retrieve all index data with the browse endpoint.
     *   - `addObject`: allowed to add or update a records in the index.
     *   - `deleteObject`: allowed to delete an existing record.
     *   - `listIndexes`: allowed to get a list of all existing indices.
     *   - `deleteIndex`: allowed to delete an index.
     *   - <span pulumi-lang-nodejs="`settings`" pulumi-lang-dotnet="`Settings`" pulumi-lang-go="`settings`" pulumi-lang-python="`settings`" pulumi-lang-yaml="`settings`" pulumi-lang-java="`settings`" pulumi-lang-hcl="`settings`">`settings`</span>: allowed to read all index settings.
     *   - `editSettings`: allowed to update all index settings.
     *   - <span pulumi-lang-nodejs="`analytics`" pulumi-lang-dotnet="`Analytics`" pulumi-lang-go="`analytics`" pulumi-lang-python="`analytics`" pulumi-lang-yaml="`analytics`" pulumi-lang-java="`analytics`" pulumi-lang-hcl="`analytics`">`analytics`</span>: allowed to retrieve data with the Analytics API.
     *   - <span pulumi-lang-nodejs="`recommendation`" pulumi-lang-dotnet="`Recommendation`" pulumi-lang-go="`recommendation`" pulumi-lang-python="`recommendation`" pulumi-lang-yaml="`recommendation`" pulumi-lang-java="`recommendation`" pulumi-lang-hcl="`recommendation`">`recommendation`</span>: allowed to interact with the Recommendation API.
     *   - <span pulumi-lang-nodejs="`usage`" pulumi-lang-dotnet="`Usage`" pulumi-lang-go="`usage`" pulumi-lang-python="`usage`" pulumi-lang-yaml="`usage`" pulumi-lang-java="`usage`" pulumi-lang-hcl="`usage`">`usage`</span> allowed to retrieve data with the Usage API.
     *   - `nluReadAnswers`: allowed to perform semantic search with the Answers API.
     *   - <span pulumi-lang-nodejs="`logs`" pulumi-lang-dotnet="`Logs`" pulumi-lang-go="`logs`" pulumi-lang-python="`logs`" pulumi-lang-yaml="`logs`" pulumi-lang-java="`logs`" pulumi-lang-hcl="`logs`">`logs`</span>: allowed to query the logs.
     *   - `seeUnretrievableAttributes`: allowed to retrieve unretrievableAttributes for all operations that return records.
     */
    declare public readonly acls: pulumi.Output<string[]>;
    declare public readonly apiKeyId: pulumi.Output<string>;
    /**
     * The unix time at which the key has been created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Description of the API key.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Unix timestamp of the date at which the key expires. RFC3339 format. Will not expire per default.
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * List of targeted indices. You can target all indices starting with a prefix or ending with a suffix using the ‘*’ character. For example, “dev_*” matches all indices starting with “dev_” and “*_dev” matches all indices ending with “_dev”.
     */
    declare public readonly indexes: pulumi.Output<string[] | undefined>;
    /**
     * The created key.
     */
    declare public /*out*/ readonly key: pulumi.Output<string>;
    /**
     * Maximum number of hits this API key can retrieve in one call. This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    declare public readonly maxHitsPerQuery: pulumi.Output<number | undefined>;
    /**
     * Maximum number of API calls allowed from an IP address per hour.Each time an API call is performed with this key, a check is performed. If the IP at the source of the call did more than this number of calls in the last hour, a 429 code is returned.
     *
     * This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    declare public readonly maxQueriesPerIpPerHour: pulumi.Output<number | undefined>;
    /**
     * List of referrers that can perform an operation. You can use the “*” (asterisk) character as a wildcard to match subdomains, or all pages of a website. For example, `"https://algolia.com/\*"` matches all referrers starting with `"https://algolia.com/"`, and `"\*.algolia.com"` matches all referrers ending with `".algolia.com"`. If you want to allow all possible referrers from the `algolia.com` domain, you can use `"\*algolia.com/\*"`.
     */
    declare public readonly referers: pulumi.Output<string[] | undefined>;

    /**
     * Create a ApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiKeyArgs | ApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiKeyState | undefined;
            resourceInputs["acls"] = state?.acls;
            resourceInputs["apiKeyId"] = state?.apiKeyId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["indexes"] = state?.indexes;
            resourceInputs["key"] = state?.key;
            resourceInputs["maxHitsPerQuery"] = state?.maxHitsPerQuery;
            resourceInputs["maxQueriesPerIpPerHour"] = state?.maxQueriesPerIpPerHour;
            resourceInputs["referers"] = state?.referers;
        } else {
            const args = argsOrState as ApiKeyArgs | undefined;
            if (args?.acls === undefined && !opts.urn) {
                throw new Error("Missing required property 'acls'");
            }
            resourceInputs["acls"] = args?.acls;
            resourceInputs["apiKeyId"] = args?.apiKeyId;
            resourceInputs["description"] = args?.description;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["indexes"] = args?.indexes;
            resourceInputs["maxHitsPerQuery"] = args?.maxHitsPerQuery;
            resourceInputs["maxQueriesPerIpPerHour"] = args?.maxQueriesPerIpPerHour;
            resourceInputs["referers"] = args?.referers;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ApiKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ApiKey resources.
 */
export interface ApiKeyState {
    /**
     * Set of permissions associated with the key.
     * The possible ACLs are:
     *   - <span pulumi-lang-nodejs="`search`" pulumi-lang-dotnet="`Search`" pulumi-lang-go="`search`" pulumi-lang-python="`search`" pulumi-lang-yaml="`search`" pulumi-lang-java="`search`" pulumi-lang-hcl="`search`">`search`</span>: allowed to perform search operations.
     *   - <span pulumi-lang-nodejs="`browse`" pulumi-lang-dotnet="`Browse`" pulumi-lang-go="`browse`" pulumi-lang-python="`browse`" pulumi-lang-yaml="`browse`" pulumi-lang-java="`browse`" pulumi-lang-hcl="`browse`">`browse`</span>: allowed to retrieve all index data with the browse endpoint.
     *   - `addObject`: allowed to add or update a records in the index.
     *   - `deleteObject`: allowed to delete an existing record.
     *   - `listIndexes`: allowed to get a list of all existing indices.
     *   - `deleteIndex`: allowed to delete an index.
     *   - <span pulumi-lang-nodejs="`settings`" pulumi-lang-dotnet="`Settings`" pulumi-lang-go="`settings`" pulumi-lang-python="`settings`" pulumi-lang-yaml="`settings`" pulumi-lang-java="`settings`" pulumi-lang-hcl="`settings`">`settings`</span>: allowed to read all index settings.
     *   - `editSettings`: allowed to update all index settings.
     *   - <span pulumi-lang-nodejs="`analytics`" pulumi-lang-dotnet="`Analytics`" pulumi-lang-go="`analytics`" pulumi-lang-python="`analytics`" pulumi-lang-yaml="`analytics`" pulumi-lang-java="`analytics`" pulumi-lang-hcl="`analytics`">`analytics`</span>: allowed to retrieve data with the Analytics API.
     *   - <span pulumi-lang-nodejs="`recommendation`" pulumi-lang-dotnet="`Recommendation`" pulumi-lang-go="`recommendation`" pulumi-lang-python="`recommendation`" pulumi-lang-yaml="`recommendation`" pulumi-lang-java="`recommendation`" pulumi-lang-hcl="`recommendation`">`recommendation`</span>: allowed to interact with the Recommendation API.
     *   - <span pulumi-lang-nodejs="`usage`" pulumi-lang-dotnet="`Usage`" pulumi-lang-go="`usage`" pulumi-lang-python="`usage`" pulumi-lang-yaml="`usage`" pulumi-lang-java="`usage`" pulumi-lang-hcl="`usage`">`usage`</span> allowed to retrieve data with the Usage API.
     *   - `nluReadAnswers`: allowed to perform semantic search with the Answers API.
     *   - <span pulumi-lang-nodejs="`logs`" pulumi-lang-dotnet="`Logs`" pulumi-lang-go="`logs`" pulumi-lang-python="`logs`" pulumi-lang-yaml="`logs`" pulumi-lang-java="`logs`" pulumi-lang-hcl="`logs`">`logs`</span>: allowed to query the logs.
     *   - `seeUnretrievableAttributes`: allowed to retrieve unretrievableAttributes for all operations that return records.
     */
    acls?: pulumi.Input<pulumi.Input<string>[]>;
    apiKeyId?: pulumi.Input<string>;
    /**
     * The unix time at which the key has been created.
     */
    createdAt?: pulumi.Input<number>;
    /**
     * Description of the API key.
     */
    description?: pulumi.Input<string>;
    /**
     * Unix timestamp of the date at which the key expires. RFC3339 format. Will not expire per default.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * List of targeted indices. You can target all indices starting with a prefix or ending with a suffix using the ‘*’ character. For example, “dev_*” matches all indices starting with “dev_” and “*_dev” matches all indices ending with “_dev”.
     */
    indexes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The created key.
     */
    key?: pulumi.Input<string>;
    /**
     * Maximum number of hits this API key can retrieve in one call. This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    maxHitsPerQuery?: pulumi.Input<number>;
    /**
     * Maximum number of API calls allowed from an IP address per hour.Each time an API call is performed with this key, a check is performed. If the IP at the source of the call did more than this number of calls in the last hour, a 429 code is returned.
     *
     * This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    maxQueriesPerIpPerHour?: pulumi.Input<number>;
    /**
     * List of referrers that can perform an operation. You can use the “*” (asterisk) character as a wildcard to match subdomains, or all pages of a website. For example, `"https://algolia.com/\*"` matches all referrers starting with `"https://algolia.com/"`, and `"\*.algolia.com"` matches all referrers ending with `".algolia.com"`. If you want to allow all possible referrers from the `algolia.com` domain, you can use `"\*algolia.com/\*"`.
     */
    referers?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a ApiKey resource.
 */
export interface ApiKeyArgs {
    /**
     * Set of permissions associated with the key.
     * The possible ACLs are:
     *   - <span pulumi-lang-nodejs="`search`" pulumi-lang-dotnet="`Search`" pulumi-lang-go="`search`" pulumi-lang-python="`search`" pulumi-lang-yaml="`search`" pulumi-lang-java="`search`" pulumi-lang-hcl="`search`">`search`</span>: allowed to perform search operations.
     *   - <span pulumi-lang-nodejs="`browse`" pulumi-lang-dotnet="`Browse`" pulumi-lang-go="`browse`" pulumi-lang-python="`browse`" pulumi-lang-yaml="`browse`" pulumi-lang-java="`browse`" pulumi-lang-hcl="`browse`">`browse`</span>: allowed to retrieve all index data with the browse endpoint.
     *   - `addObject`: allowed to add or update a records in the index.
     *   - `deleteObject`: allowed to delete an existing record.
     *   - `listIndexes`: allowed to get a list of all existing indices.
     *   - `deleteIndex`: allowed to delete an index.
     *   - <span pulumi-lang-nodejs="`settings`" pulumi-lang-dotnet="`Settings`" pulumi-lang-go="`settings`" pulumi-lang-python="`settings`" pulumi-lang-yaml="`settings`" pulumi-lang-java="`settings`" pulumi-lang-hcl="`settings`">`settings`</span>: allowed to read all index settings.
     *   - `editSettings`: allowed to update all index settings.
     *   - <span pulumi-lang-nodejs="`analytics`" pulumi-lang-dotnet="`Analytics`" pulumi-lang-go="`analytics`" pulumi-lang-python="`analytics`" pulumi-lang-yaml="`analytics`" pulumi-lang-java="`analytics`" pulumi-lang-hcl="`analytics`">`analytics`</span>: allowed to retrieve data with the Analytics API.
     *   - <span pulumi-lang-nodejs="`recommendation`" pulumi-lang-dotnet="`Recommendation`" pulumi-lang-go="`recommendation`" pulumi-lang-python="`recommendation`" pulumi-lang-yaml="`recommendation`" pulumi-lang-java="`recommendation`" pulumi-lang-hcl="`recommendation`">`recommendation`</span>: allowed to interact with the Recommendation API.
     *   - <span pulumi-lang-nodejs="`usage`" pulumi-lang-dotnet="`Usage`" pulumi-lang-go="`usage`" pulumi-lang-python="`usage`" pulumi-lang-yaml="`usage`" pulumi-lang-java="`usage`" pulumi-lang-hcl="`usage`">`usage`</span> allowed to retrieve data with the Usage API.
     *   - `nluReadAnswers`: allowed to perform semantic search with the Answers API.
     *   - <span pulumi-lang-nodejs="`logs`" pulumi-lang-dotnet="`Logs`" pulumi-lang-go="`logs`" pulumi-lang-python="`logs`" pulumi-lang-yaml="`logs`" pulumi-lang-java="`logs`" pulumi-lang-hcl="`logs`">`logs`</span>: allowed to query the logs.
     *   - `seeUnretrievableAttributes`: allowed to retrieve unretrievableAttributes for all operations that return records.
     */
    acls: pulumi.Input<pulumi.Input<string>[]>;
    apiKeyId?: pulumi.Input<string>;
    /**
     * Description of the API key.
     */
    description?: pulumi.Input<string>;
    /**
     * Unix timestamp of the date at which the key expires. RFC3339 format. Will not expire per default.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * List of targeted indices. You can target all indices starting with a prefix or ending with a suffix using the ‘*’ character. For example, “dev_*” matches all indices starting with “dev_” and “*_dev” matches all indices ending with “_dev”.
     */
    indexes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Maximum number of hits this API key can retrieve in one call. This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    maxHitsPerQuery?: pulumi.Input<number>;
    /**
     * Maximum number of API calls allowed from an IP address per hour.Each time an API call is performed with this key, a check is performed. If the IP at the source of the call did more than this number of calls in the last hour, a 429 code is returned.
     *
     * This parameter can be used to protect you from attempts at retrieving your entire index contents by massively querying the index.
     */
    maxQueriesPerIpPerHour?: pulumi.Input<number>;
    /**
     * List of referrers that can perform an operation. You can use the “*” (asterisk) character as a wildcard to match subdomains, or all pages of a website. For example, `"https://algolia.com/\*"` matches all referrers starting with `"https://algolia.com/"`, and `"\*.algolia.com"` matches all referrers ending with `".algolia.com"`. If you want to allow all possible referrers from the `algolia.com` domain, you can use `"\*algolia.com/\*"`.
     */
    referers?: pulumi.Input<pulumi.Input<string>[]>;
}
