// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiKeyArgs, ApiKeyState } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { GetIndexArgs, GetIndexResult, GetIndexOutputArgs } from "./getIndex";
export const getIndex: typeof import("./getIndex").getIndex = null as any;
export const getIndexOutput: typeof import("./getIndex").getIndexOutput = null as any;
utilities.lazyLoad(exports, ["getIndex","getIndexOutput"], () => require("./getIndex"));

export { GetVirtualIndexArgs, GetVirtualIndexResult, GetVirtualIndexOutputArgs } from "./getVirtualIndex";
export const getVirtualIndex: typeof import("./getVirtualIndex").getVirtualIndex = null as any;
export const getVirtualIndexOutput: typeof import("./getVirtualIndex").getVirtualIndexOutput = null as any;
utilities.lazyLoad(exports, ["getVirtualIndex","getVirtualIndexOutput"], () => require("./getVirtualIndex"));

export { IndexArgs, IndexState } from "./index_";
export type Index = import("./index_").Index;
export const Index: typeof import("./index_").Index = null as any;
utilities.lazyLoad(exports, ["Index"], () => require("./index_"));

export * from "./provider";
import { Provider } from "./provider";

export { QuerySuggestionsArgs, QuerySuggestionsState } from "./querySuggestions";
export type QuerySuggestions = import("./querySuggestions").QuerySuggestions;
export const QuerySuggestions: typeof import("./querySuggestions").QuerySuggestions = null as any;
utilities.lazyLoad(exports, ["QuerySuggestions"], () => require("./querySuggestions"));

export { RuleArgs, RuleState } from "./rule";
export type Rule = import("./rule").Rule;
export const Rule: typeof import("./rule").Rule = null as any;
utilities.lazyLoad(exports, ["Rule"], () => require("./rule"));

export { SynonymsArgs, SynonymsState } from "./synonyms";
export type Synonyms = import("./synonyms").Synonyms;
export const Synonyms: typeof import("./synonyms").Synonyms = null as any;
utilities.lazyLoad(exports, ["Synonyms"], () => require("./synonyms"));

export { VirtualIndexArgs, VirtualIndexState } from "./virtualIndex";
export type VirtualIndex = import("./virtualIndex").VirtualIndex;
export const VirtualIndex: typeof import("./virtualIndex").VirtualIndex = null as any;
utilities.lazyLoad(exports, ["VirtualIndex"], () => require("./virtualIndex"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "algolia:index/apiKey:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "algolia:index/index:Index":
                return new Index(name, <any>undefined, { urn })
            case "algolia:index/querySuggestions:QuerySuggestions":
                return new QuerySuggestions(name, <any>undefined, { urn })
            case "algolia:index/rule:Rule":
                return new Rule(name, <any>undefined, { urn })
            case "algolia:index/synonyms:Synonyms":
                return new Synonyms(name, <any>undefined, { urn })
            case "algolia:index/virtualIndex:VirtualIndex":
                return new VirtualIndex(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("algolia", "index/apiKey", _module)
pulumi.runtime.registerResourceModule("algolia", "index/index", _module)
pulumi.runtime.registerResourceModule("algolia", "index/querySuggestions", _module)
pulumi.runtime.registerResourceModule("algolia", "index/rule", _module)
pulumi.runtime.registerResourceModule("algolia", "index/synonyms", _module)
pulumi.runtime.registerResourceModule("algolia", "index/virtualIndex", _module)
pulumi.runtime.registerResourcePackage("algolia", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:algolia") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
