// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Index extends pulumi.CustomResource {
    /**
     * Get an existing Index resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IndexState, opts?: pulumi.CustomResourceOptions): Index {
        return new Index(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/index:Index';

    /**
     * Returns true if the given object is an instance of Index.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Index {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Index.__pulumiType;
    }

    /**
     * The configuration for advanced features in index setting.
     */
    declare public readonly advancedConfig: pulumi.Output<outputs.IndexAdvancedConfig | undefined>;
    /**
     * The configuration for attributes.
     */
    declare public readonly attributesConfig: pulumi.Output<outputs.IndexAttributesConfig | undefined>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    declare public readonly deletionProtection: pulumi.Output<boolean | undefined>;
    /**
     * Whether to enable the Personalization feature.
     */
    declare public readonly enablePersonalization: pulumi.Output<boolean | undefined>;
    /**
     * Whether Rules should be globally enabled.
     */
    declare public readonly enableRules: pulumi.Output<boolean | undefined>;
    /**
     * The configuration for faceting.
     */
    declare public readonly facetingConfig: pulumi.Output<outputs.IndexFacetingConfig | undefined>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    declare public readonly highlightAndSnippetConfig: pulumi.Output<outputs.IndexHighlightAndSnippetConfig | undefined>;
    declare public readonly indexId: pulumi.Output<string>;
    /**
     * The configuration for languages in index setting.
     */
    declare public readonly languagesConfig: pulumi.Output<outputs.IndexLanguagesConfig | undefined>;
    /**
     * Name of the index / replica index. For creating virtual replica, use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The configuration for pagination in index setting.
     */
    declare public readonly paginationConfig: pulumi.Output<outputs.IndexPaginationConfig | undefined>;
    /**
     * The configuration for performance in index setting.
     */
    declare public readonly performanceConfig: pulumi.Output<outputs.IndexPerformanceConfig | undefined>;
    /**
     * The name of the existing primary index name. This field is used to create a replica index.
     */
    declare public readonly primaryIndexName: pulumi.Output<string | undefined>;
    /**
     * The configuration for query strategy in index setting.
     */
    declare public readonly queryStrategyConfig: pulumi.Output<outputs.IndexQueryStrategyConfig | undefined>;
    /**
     * The configuration for ranking.
     */
    declare public readonly rankingConfig: pulumi.Output<outputs.IndexRankingConfig | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.IndexTimeouts | undefined>;
    /**
     * The configuration for typos in index setting.
     */
    declare public readonly typosConfig: pulumi.Output<outputs.IndexTyposConfig | undefined>;
    /**
     * **Deprecated:** Use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead. Whether the index is virtual index. If true, applying the params listed in the [doc](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/replicas/#unsupported-parameters) will be ignored.
     *
     * @deprecated Deprecated
     */
    declare public readonly virtual: pulumi.Output<boolean | undefined>;

    /**
     * Create a Index resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IndexArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IndexArgs | IndexState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IndexState | undefined;
            resourceInputs["advancedConfig"] = state?.advancedConfig;
            resourceInputs["attributesConfig"] = state?.attributesConfig;
            resourceInputs["deletionProtection"] = state?.deletionProtection;
            resourceInputs["enablePersonalization"] = state?.enablePersonalization;
            resourceInputs["enableRules"] = state?.enableRules;
            resourceInputs["facetingConfig"] = state?.facetingConfig;
            resourceInputs["highlightAndSnippetConfig"] = state?.highlightAndSnippetConfig;
            resourceInputs["indexId"] = state?.indexId;
            resourceInputs["languagesConfig"] = state?.languagesConfig;
            resourceInputs["name"] = state?.name;
            resourceInputs["paginationConfig"] = state?.paginationConfig;
            resourceInputs["performanceConfig"] = state?.performanceConfig;
            resourceInputs["primaryIndexName"] = state?.primaryIndexName;
            resourceInputs["queryStrategyConfig"] = state?.queryStrategyConfig;
            resourceInputs["rankingConfig"] = state?.rankingConfig;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["typosConfig"] = state?.typosConfig;
            resourceInputs["virtual"] = state?.virtual;
        } else {
            const args = argsOrState as IndexArgs | undefined;
            resourceInputs["advancedConfig"] = args?.advancedConfig;
            resourceInputs["attributesConfig"] = args?.attributesConfig;
            resourceInputs["deletionProtection"] = args?.deletionProtection;
            resourceInputs["enablePersonalization"] = args?.enablePersonalization;
            resourceInputs["enableRules"] = args?.enableRules;
            resourceInputs["facetingConfig"] = args?.facetingConfig;
            resourceInputs["highlightAndSnippetConfig"] = args?.highlightAndSnippetConfig;
            resourceInputs["indexId"] = args?.indexId;
            resourceInputs["languagesConfig"] = args?.languagesConfig;
            resourceInputs["name"] = args?.name;
            resourceInputs["paginationConfig"] = args?.paginationConfig;
            resourceInputs["performanceConfig"] = args?.performanceConfig;
            resourceInputs["primaryIndexName"] = args?.primaryIndexName;
            resourceInputs["queryStrategyConfig"] = args?.queryStrategyConfig;
            resourceInputs["rankingConfig"] = args?.rankingConfig;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["typosConfig"] = args?.typosConfig;
            resourceInputs["virtual"] = args?.virtual;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Index.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Index resources.
 */
export interface IndexState {
    /**
     * The configuration for advanced features in index setting.
     */
    advancedConfig?: pulumi.Input<inputs.IndexAdvancedConfig>;
    /**
     * The configuration for attributes.
     */
    attributesConfig?: pulumi.Input<inputs.IndexAttributesConfig>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * Whether to enable the Personalization feature.
     */
    enablePersonalization?: pulumi.Input<boolean>;
    /**
     * Whether Rules should be globally enabled.
     */
    enableRules?: pulumi.Input<boolean>;
    /**
     * The configuration for faceting.
     */
    facetingConfig?: pulumi.Input<inputs.IndexFacetingConfig>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    highlightAndSnippetConfig?: pulumi.Input<inputs.IndexHighlightAndSnippetConfig>;
    indexId?: pulumi.Input<string>;
    /**
     * The configuration for languages in index setting.
     */
    languagesConfig?: pulumi.Input<inputs.IndexLanguagesConfig>;
    /**
     * Name of the index / replica index. For creating virtual replica, use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead.
     */
    name?: pulumi.Input<string>;
    /**
     * The configuration for pagination in index setting.
     */
    paginationConfig?: pulumi.Input<inputs.IndexPaginationConfig>;
    /**
     * The configuration for performance in index setting.
     */
    performanceConfig?: pulumi.Input<inputs.IndexPerformanceConfig>;
    /**
     * The name of the existing primary index name. This field is used to create a replica index.
     */
    primaryIndexName?: pulumi.Input<string>;
    /**
     * The configuration for query strategy in index setting.
     */
    queryStrategyConfig?: pulumi.Input<inputs.IndexQueryStrategyConfig>;
    /**
     * The configuration for ranking.
     */
    rankingConfig?: pulumi.Input<inputs.IndexRankingConfig>;
    timeouts?: pulumi.Input<inputs.IndexTimeouts>;
    /**
     * The configuration for typos in index setting.
     */
    typosConfig?: pulumi.Input<inputs.IndexTyposConfig>;
    /**
     * **Deprecated:** Use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead. Whether the index is virtual index. If true, applying the params listed in the [doc](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/replicas/#unsupported-parameters) will be ignored.
     *
     * @deprecated Deprecated
     */
    virtual?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Index resource.
 */
export interface IndexArgs {
    /**
     * The configuration for advanced features in index setting.
     */
    advancedConfig?: pulumi.Input<inputs.IndexAdvancedConfig>;
    /**
     * The configuration for attributes.
     */
    attributesConfig?: pulumi.Input<inputs.IndexAttributesConfig>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * Whether to enable the Personalization feature.
     */
    enablePersonalization?: pulumi.Input<boolean>;
    /**
     * Whether Rules should be globally enabled.
     */
    enableRules?: pulumi.Input<boolean>;
    /**
     * The configuration for faceting.
     */
    facetingConfig?: pulumi.Input<inputs.IndexFacetingConfig>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    highlightAndSnippetConfig?: pulumi.Input<inputs.IndexHighlightAndSnippetConfig>;
    indexId?: pulumi.Input<string>;
    /**
     * The configuration for languages in index setting.
     */
    languagesConfig?: pulumi.Input<inputs.IndexLanguagesConfig>;
    /**
     * Name of the index / replica index. For creating virtual replica, use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead.
     */
    name?: pulumi.Input<string>;
    /**
     * The configuration for pagination in index setting.
     */
    paginationConfig?: pulumi.Input<inputs.IndexPaginationConfig>;
    /**
     * The configuration for performance in index setting.
     */
    performanceConfig?: pulumi.Input<inputs.IndexPerformanceConfig>;
    /**
     * The name of the existing primary index name. This field is used to create a replica index.
     */
    primaryIndexName?: pulumi.Input<string>;
    /**
     * The configuration for query strategy in index setting.
     */
    queryStrategyConfig?: pulumi.Input<inputs.IndexQueryStrategyConfig>;
    /**
     * The configuration for ranking.
     */
    rankingConfig?: pulumi.Input<inputs.IndexRankingConfig>;
    timeouts?: pulumi.Input<inputs.IndexTimeouts>;
    /**
     * The configuration for typos in index setting.
     */
    typosConfig?: pulumi.Input<inputs.IndexTyposConfig>;
    /**
     * **Deprecated:** Use <span pulumi-lang-nodejs="`algolia.VirtualIndex`" pulumi-lang-dotnet="`algolia.VirtualIndex`" pulumi-lang-go="`VirtualIndex`" pulumi-lang-python="`VirtualIndex`" pulumi-lang-yaml="`algolia.VirtualIndex`" pulumi-lang-java="`algolia.VirtualIndex`" pulumi-lang-hcl="`algolia_virtual_index`">`algolia.VirtualIndex`</span> resource instead. Whether the index is virtual index. If true, applying the params listed in the [doc](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/replicas/#unsupported-parameters) will be ignored.
     *
     * @deprecated Deprecated
     */
    virtual?: pulumi.Input<boolean>;
}
