// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Rule extends pulumi.CustomResource {
    /**
     * Get an existing Rule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleState, opts?: pulumi.CustomResourceOptions): Rule {
        return new Rule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/rule:Rule';

    /**
     * Returns true if the given object is an instance of Rule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Rule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Rule.__pulumiType;
    }

    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    declare public readonly conditions: pulumi.Output<outputs.RuleCondition[] | undefined>;
    /**
     * Consequence of the Rule. 
     * At least one of the following object must be used:
     * - params
     * - promote
     * - hide
     * -<span pulumi-lang-nodejs=" userData
     * " pulumi-lang-dotnet=" UserData
     * " pulumi-lang-go=" userData
     * " pulumi-lang-python=" user_data
     * " pulumi-lang-yaml=" userData
     * " pulumi-lang-java=" userData
     * " pulumi-lang-hcl=" user_data
     * "> userData
     * </span>
     */
    declare public readonly consequence: pulumi.Output<outputs.RuleConsequence>;
    /**
     * This field is intended for Rule management purposes, in particular to ease searching for Rules and presenting them to human readers. It is not interpreted by the API.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether the Rule is enabled. Disabled Rules remain in the index, but are not applied at query time.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Name of the index to apply rule.
     */
    declare public readonly indexName: pulumi.Output<string>;
    /**
     * Unique identifier for the Rule (format: `[A-Za-z0-9_-]+`).
     */
    declare public readonly objectId: pulumi.Output<string>;
    declare public readonly ruleId: pulumi.Output<string>;
    /**
     * Objects to promote as hits.
     */
    declare public readonly validities: pulumi.Output<outputs.RuleValidity[] | undefined>;

    /**
     * Create a Rule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleArgs | RuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleState | undefined;
            resourceInputs["conditions"] = state?.conditions;
            resourceInputs["consequence"] = state?.consequence;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["indexName"] = state?.indexName;
            resourceInputs["objectId"] = state?.objectId;
            resourceInputs["ruleId"] = state?.ruleId;
            resourceInputs["validities"] = state?.validities;
        } else {
            const args = argsOrState as RuleArgs | undefined;
            if (args?.consequence === undefined && !opts.urn) {
                throw new Error("Missing required property 'consequence'");
            }
            if (args?.indexName === undefined && !opts.urn) {
                throw new Error("Missing required property 'indexName'");
            }
            if (args?.objectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'objectId'");
            }
            resourceInputs["conditions"] = args?.conditions;
            resourceInputs["consequence"] = args?.consequence;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["indexName"] = args?.indexName;
            resourceInputs["objectId"] = args?.objectId;
            resourceInputs["ruleId"] = args?.ruleId;
            resourceInputs["validities"] = args?.validities;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Rule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Rule resources.
 */
export interface RuleState {
    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.RuleCondition>[]>;
    /**
     * Consequence of the Rule. 
     * At least one of the following object must be used:
     * - params
     * - promote
     * - hide
     * -<span pulumi-lang-nodejs=" userData
     * " pulumi-lang-dotnet=" UserData
     * " pulumi-lang-go=" userData
     * " pulumi-lang-python=" user_data
     * " pulumi-lang-yaml=" userData
     * " pulumi-lang-java=" userData
     * " pulumi-lang-hcl=" user_data
     * "> userData
     * </span>
     */
    consequence?: pulumi.Input<inputs.RuleConsequence>;
    /**
     * This field is intended for Rule management purposes, in particular to ease searching for Rules and presenting them to human readers. It is not interpreted by the API.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether the Rule is enabled. Disabled Rules remain in the index, but are not applied at query time.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Name of the index to apply rule.
     */
    indexName?: pulumi.Input<string>;
    /**
     * Unique identifier for the Rule (format: `[A-Za-z0-9_-]+`).
     */
    objectId?: pulumi.Input<string>;
    ruleId?: pulumi.Input<string>;
    /**
     * Objects to promote as hits.
     */
    validities?: pulumi.Input<pulumi.Input<inputs.RuleValidity>[]>;
}

/**
 * The set of arguments for constructing a Rule resource.
 */
export interface RuleArgs {
    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.RuleCondition>[]>;
    /**
     * Consequence of the Rule. 
     * At least one of the following object must be used:
     * - params
     * - promote
     * - hide
     * -<span pulumi-lang-nodejs=" userData
     * " pulumi-lang-dotnet=" UserData
     * " pulumi-lang-go=" userData
     * " pulumi-lang-python=" user_data
     * " pulumi-lang-yaml=" userData
     * " pulumi-lang-java=" userData
     * " pulumi-lang-hcl=" user_data
     * "> userData
     * </span>
     */
    consequence: pulumi.Input<inputs.RuleConsequence>;
    /**
     * This field is intended for Rule management purposes, in particular to ease searching for Rules and presenting them to human readers. It is not interpreted by the API.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether the Rule is enabled. Disabled Rules remain in the index, but are not applied at query time.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Name of the index to apply rule.
     */
    indexName: pulumi.Input<string>;
    /**
     * Unique identifier for the Rule (format: `[A-Za-z0-9_-]+`).
     */
    objectId: pulumi.Input<string>;
    ruleId?: pulumi.Input<string>;
    /**
     * Objects to promote as hits.
     */
    validities?: pulumi.Input<pulumi.Input<inputs.RuleValidity>[]>;
}
