// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Synonyms extends pulumi.CustomResource {
    /**
     * Get an existing Synonyms resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SynonymsState, opts?: pulumi.CustomResourceOptions): Synonyms {
        return new Synonyms(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/synonyms:Synonyms';

    /**
     * Returns true if the given object is an instance of Synonyms.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Synonyms {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Synonyms.__pulumiType;
    }

    /**
     * Name of the index to apply synonyms.
     */
    declare public readonly indexName: pulumi.Output<string>;
    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    declare public readonly synonyms: pulumi.Output<outputs.SynonymsSynonym[]>;
    declare public readonly synonymsId: pulumi.Output<string>;

    /**
     * Create a Synonyms resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SynonymsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SynonymsArgs | SynonymsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SynonymsState | undefined;
            resourceInputs["indexName"] = state?.indexName;
            resourceInputs["synonyms"] = state?.synonyms;
            resourceInputs["synonymsId"] = state?.synonymsId;
        } else {
            const args = argsOrState as SynonymsArgs | undefined;
            if (args?.indexName === undefined && !opts.urn) {
                throw new Error("Missing required property 'indexName'");
            }
            if (args?.synonyms === undefined && !opts.urn) {
                throw new Error("Missing required property 'synonyms'");
            }
            resourceInputs["indexName"] = args?.indexName;
            resourceInputs["synonyms"] = args?.synonyms;
            resourceInputs["synonymsId"] = args?.synonymsId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Synonyms.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Synonyms resources.
 */
export interface SynonymsState {
    /**
     * Name of the index to apply synonyms.
     */
    indexName?: pulumi.Input<string>;
    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    synonyms?: pulumi.Input<pulumi.Input<inputs.SynonymsSynonym>[]>;
    synonymsId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Synonyms resource.
 */
export interface SynonymsArgs {
    /**
     * Name of the index to apply synonyms.
     */
    indexName: pulumi.Input<string>;
    /**
     * A list of conditions that should apply to activate a Rule. You can use up to 25 conditions per Rule.
     */
    synonyms: pulumi.Input<pulumi.Input<inputs.SynonymsSynonym>[]>;
    synonymsId?: pulumi.Input<string>;
}
