// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("algolia");

/**
 * The API key to access algolia resources. Defaults to the env variable `ALGOLIA_API_KEY`.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * The ID of the application. Defaults to the env variable `ALGOLIA_APP_ID`.
 */
export declare const appId: string | undefined;
Object.defineProperty(exports, "appId", {
    get() {
        return __config.get("appId");
    },
    enumerable: true,
});

