services:
  devcontainer:
    image: nvidia/cuda:13.0.0-devel-ubuntu22.04
    command: sleep infinity
    environment:
      SSH_AUTH_SOCK: /ssh-agent.sock
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/$GOOGLE_APPLICATION_CREDENTIALS
      NX_TUI: false
    volumes:
      - ../../..:/workspaces:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.gcp:/var/secrets:cached
      - type: bind
        source: ${SSH_AUTH_SOCK:-/tmp/ssh-agent.sock}
        target: /ssh-agent.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
