config:
  gcp:project: news-research-dev
  gcp:region: us-central1
  github:owner: ajaremko
  platform:kmsLocation: us
  platform:archiveLocation: US
  platform:archiveTTL: 30
  platform:githubOrg: ajaremko
  platform:githubRepo: news-research
