// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIndex(args: GetIndexArgs, opts?: pulumi.InvokeOptions): Promise<GetIndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("algolia:index/getIndex:getIndex", {
        "id": args.id,
        "name": args.name,
        "paginationConfigs": args.paginationConfigs,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIndex.
 */
export interface GetIndexArgs {
    id?: string;
    name: string;
    paginationConfigs?: inputs.GetIndexPaginationConfig[];
}

/**
 * A collection of values returned by getIndex.
 */
export interface GetIndexResult {
    readonly advancedConfigs: outputs.GetIndexAdvancedConfig[];
    readonly attributesConfigs: outputs.GetIndexAttributesConfig[];
    readonly enablePersonalization: boolean;
    readonly enableRules: boolean;
    readonly facetingConfigs: outputs.GetIndexFacetingConfig[];
    readonly highlightAndSnippetConfigs: outputs.GetIndexHighlightAndSnippetConfig[];
    readonly id: string;
    readonly languagesConfigs: outputs.GetIndexLanguagesConfig[];
    readonly name: string;
    readonly paginationConfigs?: outputs.GetIndexPaginationConfig[];
    readonly performanceConfigs: outputs.GetIndexPerformanceConfig[];
    readonly primaryIndexName: string;
    readonly queryStrategyConfigs: outputs.GetIndexQueryStrategyConfig[];
    readonly rankingConfigs: outputs.GetIndexRankingConfig[];
    readonly typosConfigs: outputs.GetIndexTyposConfig[];
    readonly virtual: boolean;
}
export function getIndexOutput(args: GetIndexOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("algolia:index/getIndex:getIndex", {
        "id": args.id,
        "name": args.name,
        "paginationConfigs": args.paginationConfigs,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getIndex.
 */
export interface GetIndexOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    paginationConfigs?: pulumi.Input<pulumi.Input<inputs.GetIndexPaginationConfigArgs>[]>;
}
