// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVirtualIndex(args: GetVirtualIndexArgs, opts?: pulumi.InvokeOptions): Promise<GetVirtualIndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("algolia:index/getVirtualIndex:getVirtualIndex", {
        "id": args.id,
        "name": args.name,
        "paginationConfigs": args.paginationConfigs,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVirtualIndex.
 */
export interface GetVirtualIndexArgs {
    id?: string;
    name: string;
    paginationConfigs?: inputs.GetVirtualIndexPaginationConfig[];
}

/**
 * A collection of values returned by getVirtualIndex.
 */
export interface GetVirtualIndexResult {
    readonly advancedConfigs: outputs.GetVirtualIndexAdvancedConfig[];
    readonly attributesConfigs: outputs.GetVirtualIndexAttributesConfig[];
    readonly enablePersonalization: boolean;
    readonly enableRules: boolean;
    readonly facetingConfigs: outputs.GetVirtualIndexFacetingConfig[];
    readonly highlightAndSnippetConfigs: outputs.GetVirtualIndexHighlightAndSnippetConfig[];
    readonly id: string;
    readonly languagesConfigs: outputs.GetVirtualIndexLanguagesConfig[];
    readonly name: string;
    readonly paginationConfigs?: outputs.GetVirtualIndexPaginationConfig[];
    readonly performanceConfigs: outputs.GetVirtualIndexPerformanceConfig[];
    readonly primaryIndexName: string;
    readonly queryStrategyConfigs: outputs.GetVirtualIndexQueryStrategyConfig[];
    readonly rankingConfigs: outputs.GetVirtualIndexRankingConfig[];
    readonly typosConfigs: outputs.GetVirtualIndexTyposConfig[];
}
export function getVirtualIndexOutput(args: GetVirtualIndexOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVirtualIndexResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("algolia:index/getVirtualIndex:getVirtualIndex", {
        "id": args.id,
        "name": args.name,
        "paginationConfigs": args.paginationConfigs,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVirtualIndex.
 */
export interface GetVirtualIndexOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    paginationConfigs?: pulumi.Input<pulumi.Input<inputs.GetVirtualIndexPaginationConfigArgs>[]>;
}
