// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class QuerySuggestions extends pulumi.CustomResource {
    /**
     * Get an existing QuerySuggestions resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: QuerySuggestionsState, opts?: pulumi.CustomResourceOptions): QuerySuggestions {
        return new QuerySuggestions(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/querySuggestions:QuerySuggestions';

    /**
     * Returns true if the given object is an instance of QuerySuggestions.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is QuerySuggestions {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === QuerySuggestions.__pulumiType;
    }

    /**
     * A list of words and patterns to exclude from the Query Suggestions index.
     */
    declare public readonly excludes: pulumi.Output<string[] | undefined>;
    /**
     * Index name to target.
     */
    declare public readonly indexName: pulumi.Output<string>;
    /**
     * A list of languages used to de-duplicate singular and plural suggestions.
     */
    declare public readonly languages: pulumi.Output<string[] | undefined>;
    declare public readonly querySuggestionsId: pulumi.Output<string>;
    /**
     * Region to create the index in. "us", "eu", "de" are supported. Defaults to "us" when not specified.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * A list of source indices used to generate a Query Suggestions index.
     */
    declare public readonly sourceIndices: pulumi.Output<outputs.QuerySuggestionsSourceIndex[]>;

    /**
     * Create a QuerySuggestions resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: QuerySuggestionsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: QuerySuggestionsArgs | QuerySuggestionsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as QuerySuggestionsState | undefined;
            resourceInputs["excludes"] = state?.excludes;
            resourceInputs["indexName"] = state?.indexName;
            resourceInputs["languages"] = state?.languages;
            resourceInputs["querySuggestionsId"] = state?.querySuggestionsId;
            resourceInputs["region"] = state?.region;
            resourceInputs["sourceIndices"] = state?.sourceIndices;
        } else {
            const args = argsOrState as QuerySuggestionsArgs | undefined;
            if (args?.indexName === undefined && !opts.urn) {
                throw new Error("Missing required property 'indexName'");
            }
            if (args?.sourceIndices === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceIndices'");
            }
            resourceInputs["excludes"] = args?.excludes;
            resourceInputs["indexName"] = args?.indexName;
            resourceInputs["languages"] = args?.languages;
            resourceInputs["querySuggestionsId"] = args?.querySuggestionsId;
            resourceInputs["region"] = args?.region;
            resourceInputs["sourceIndices"] = args?.sourceIndices;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(QuerySuggestions.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering QuerySuggestions resources.
 */
export interface QuerySuggestionsState {
    /**
     * A list of words and patterns to exclude from the Query Suggestions index.
     */
    excludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Index name to target.
     */
    indexName?: pulumi.Input<string>;
    /**
     * A list of languages used to de-duplicate singular and plural suggestions.
     */
    languages?: pulumi.Input<pulumi.Input<string>[]>;
    querySuggestionsId?: pulumi.Input<string>;
    /**
     * Region to create the index in. "us", "eu", "de" are supported. Defaults to "us" when not specified.
     */
    region?: pulumi.Input<string>;
    /**
     * A list of source indices used to generate a Query Suggestions index.
     */
    sourceIndices?: pulumi.Input<pulumi.Input<inputs.QuerySuggestionsSourceIndex>[]>;
}

/**
 * The set of arguments for constructing a QuerySuggestions resource.
 */
export interface QuerySuggestionsArgs {
    /**
     * A list of words and patterns to exclude from the Query Suggestions index.
     */
    excludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Index name to target.
     */
    indexName: pulumi.Input<string>;
    /**
     * A list of languages used to de-duplicate singular and plural suggestions.
     */
    languages?: pulumi.Input<pulumi.Input<string>[]>;
    querySuggestionsId?: pulumi.Input<string>;
    /**
     * Region to create the index in. "us", "eu", "de" are supported. Defaults to "us" when not specified.
     */
    region?: pulumi.Input<string>;
    /**
     * A list of source indices used to generate a Query Suggestions index.
     */
    sourceIndices: pulumi.Input<pulumi.Input<inputs.QuerySuggestionsSourceIndex>[]>;
}
