// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class VirtualIndex extends pulumi.CustomResource {
    /**
     * Get an existing VirtualIndex resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VirtualIndexState, opts?: pulumi.CustomResourceOptions): VirtualIndex {
        return new VirtualIndex(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'algolia:index/virtualIndex:VirtualIndex';

    /**
     * Returns true if the given object is an instance of VirtualIndex.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VirtualIndex {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VirtualIndex.__pulumiType;
    }

    /**
     * The configuration for advanced features in index setting.
     */
    declare public readonly advancedConfig: pulumi.Output<outputs.VirtualIndexAdvancedConfig | undefined>;
    /**
     * The configuration for attributes.
     */
    declare public readonly attributesConfig: pulumi.Output<outputs.VirtualIndexAttributesConfig | undefined>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    declare public readonly deletionProtection: pulumi.Output<boolean | undefined>;
    /**
     * Whether to enable the Personalization feature.
     */
    declare public readonly enablePersonalization: pulumi.Output<boolean | undefined>;
    /**
     * Whether Rules should be globally enabled.
     */
    declare public readonly enableRules: pulumi.Output<boolean | undefined>;
    /**
     * The configuration for faceting.
     */
    declare public readonly facetingConfig: pulumi.Output<outputs.VirtualIndexFacetingConfig | undefined>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    declare public readonly highlightAndSnippetConfig: pulumi.Output<outputs.VirtualIndexHighlightAndSnippetConfig | undefined>;
    /**
     * The configuration for languages in index setting.
     */
    declare public readonly languagesConfig: pulumi.Output<outputs.VirtualIndexLanguagesConfig | undefined>;
    /**
     * Name of the virtual index. Its name should NOT be surrounded with `virtual()`.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The configuration for pagination in index setting.
     */
    declare public readonly paginationConfig: pulumi.Output<outputs.VirtualIndexPaginationConfig | undefined>;
    /**
     * The configuration for performance in index setting.
     */
    declare public /*out*/ readonly performanceConfigs: pulumi.Output<outputs.VirtualIndexPerformanceConfig[]>;
    /**
     * The name of the existing primary index name.
     */
    declare public readonly primaryIndexName: pulumi.Output<string>;
    /**
     * The configuration for query strategy in index setting.
     */
    declare public readonly queryStrategyConfig: pulumi.Output<outputs.VirtualIndexQueryStrategyConfig | undefined>;
    /**
     * The configuration for ranking.
     */
    declare public readonly rankingConfig: pulumi.Output<outputs.VirtualIndexRankingConfig | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.VirtualIndexTimeouts | undefined>;
    /**
     * The configuration for typos in index setting.
     */
    declare public readonly typosConfig: pulumi.Output<outputs.VirtualIndexTyposConfig | undefined>;
    declare public readonly virtualIndexId: pulumi.Output<string>;

    /**
     * Create a VirtualIndex resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VirtualIndexArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VirtualIndexArgs | VirtualIndexState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VirtualIndexState | undefined;
            resourceInputs["advancedConfig"] = state?.advancedConfig;
            resourceInputs["attributesConfig"] = state?.attributesConfig;
            resourceInputs["deletionProtection"] = state?.deletionProtection;
            resourceInputs["enablePersonalization"] = state?.enablePersonalization;
            resourceInputs["enableRules"] = state?.enableRules;
            resourceInputs["facetingConfig"] = state?.facetingConfig;
            resourceInputs["highlightAndSnippetConfig"] = state?.highlightAndSnippetConfig;
            resourceInputs["languagesConfig"] = state?.languagesConfig;
            resourceInputs["name"] = state?.name;
            resourceInputs["paginationConfig"] = state?.paginationConfig;
            resourceInputs["performanceConfigs"] = state?.performanceConfigs;
            resourceInputs["primaryIndexName"] = state?.primaryIndexName;
            resourceInputs["queryStrategyConfig"] = state?.queryStrategyConfig;
            resourceInputs["rankingConfig"] = state?.rankingConfig;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["typosConfig"] = state?.typosConfig;
            resourceInputs["virtualIndexId"] = state?.virtualIndexId;
        } else {
            const args = argsOrState as VirtualIndexArgs | undefined;
            if (args?.primaryIndexName === undefined && !opts.urn) {
                throw new Error("Missing required property 'primaryIndexName'");
            }
            resourceInputs["advancedConfig"] = args?.advancedConfig;
            resourceInputs["attributesConfig"] = args?.attributesConfig;
            resourceInputs["deletionProtection"] = args?.deletionProtection;
            resourceInputs["enablePersonalization"] = args?.enablePersonalization;
            resourceInputs["enableRules"] = args?.enableRules;
            resourceInputs["facetingConfig"] = args?.facetingConfig;
            resourceInputs["highlightAndSnippetConfig"] = args?.highlightAndSnippetConfig;
            resourceInputs["languagesConfig"] = args?.languagesConfig;
            resourceInputs["name"] = args?.name;
            resourceInputs["paginationConfig"] = args?.paginationConfig;
            resourceInputs["primaryIndexName"] = args?.primaryIndexName;
            resourceInputs["queryStrategyConfig"] = args?.queryStrategyConfig;
            resourceInputs["rankingConfig"] = args?.rankingConfig;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["typosConfig"] = args?.typosConfig;
            resourceInputs["virtualIndexId"] = args?.virtualIndexId;
            resourceInputs["performanceConfigs"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VirtualIndex.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering VirtualIndex resources.
 */
export interface VirtualIndexState {
    /**
     * The configuration for advanced features in index setting.
     */
    advancedConfig?: pulumi.Input<inputs.VirtualIndexAdvancedConfig>;
    /**
     * The configuration for attributes.
     */
    attributesConfig?: pulumi.Input<inputs.VirtualIndexAttributesConfig>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * Whether to enable the Personalization feature.
     */
    enablePersonalization?: pulumi.Input<boolean>;
    /**
     * Whether Rules should be globally enabled.
     */
    enableRules?: pulumi.Input<boolean>;
    /**
     * The configuration for faceting.
     */
    facetingConfig?: pulumi.Input<inputs.VirtualIndexFacetingConfig>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    highlightAndSnippetConfig?: pulumi.Input<inputs.VirtualIndexHighlightAndSnippetConfig>;
    /**
     * The configuration for languages in index setting.
     */
    languagesConfig?: pulumi.Input<inputs.VirtualIndexLanguagesConfig>;
    /**
     * Name of the virtual index. Its name should NOT be surrounded with `virtual()`.
     */
    name?: pulumi.Input<string>;
    /**
     * The configuration for pagination in index setting.
     */
    paginationConfig?: pulumi.Input<inputs.VirtualIndexPaginationConfig>;
    /**
     * The configuration for performance in index setting.
     */
    performanceConfigs?: pulumi.Input<pulumi.Input<inputs.VirtualIndexPerformanceConfig>[]>;
    /**
     * The name of the existing primary index name.
     */
    primaryIndexName?: pulumi.Input<string>;
    /**
     * The configuration for query strategy in index setting.
     */
    queryStrategyConfig?: pulumi.Input<inputs.VirtualIndexQueryStrategyConfig>;
    /**
     * The configuration for ranking.
     */
    rankingConfig?: pulumi.Input<inputs.VirtualIndexRankingConfig>;
    timeouts?: pulumi.Input<inputs.VirtualIndexTimeouts>;
    /**
     * The configuration for typos in index setting.
     */
    typosConfig?: pulumi.Input<inputs.VirtualIndexTyposConfig>;
    virtualIndexId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VirtualIndex resource.
 */
export interface VirtualIndexArgs {
    /**
     * The configuration for advanced features in index setting.
     */
    advancedConfig?: pulumi.Input<inputs.VirtualIndexAdvancedConfig>;
    /**
     * The configuration for attributes.
     */
    attributesConfig?: pulumi.Input<inputs.VirtualIndexAttributesConfig>;
    /**
     * Whether to allow Terraform to destroy the index.  Unless this field is set to false in Terraform state, a terraform destroy or terraform apply command that deletes the instance will fail.
     */
    deletionProtection?: pulumi.Input<boolean>;
    /**
     * Whether to enable the Personalization feature.
     */
    enablePersonalization?: pulumi.Input<boolean>;
    /**
     * Whether Rules should be globally enabled.
     */
    enableRules?: pulumi.Input<boolean>;
    /**
     * The configuration for faceting.
     */
    facetingConfig?: pulumi.Input<inputs.VirtualIndexFacetingConfig>;
    /**
     * The configuration for highlight / snippet in index setting.
     */
    highlightAndSnippetConfig?: pulumi.Input<inputs.VirtualIndexHighlightAndSnippetConfig>;
    /**
     * The configuration for languages in index setting.
     */
    languagesConfig?: pulumi.Input<inputs.VirtualIndexLanguagesConfig>;
    /**
     * Name of the virtual index. Its name should NOT be surrounded with `virtual()`.
     */
    name?: pulumi.Input<string>;
    /**
     * The configuration for pagination in index setting.
     */
    paginationConfig?: pulumi.Input<inputs.VirtualIndexPaginationConfig>;
    /**
     * The name of the existing primary index name.
     */
    primaryIndexName: pulumi.Input<string>;
    /**
     * The configuration for query strategy in index setting.
     */
    queryStrategyConfig?: pulumi.Input<inputs.VirtualIndexQueryStrategyConfig>;
    /**
     * The configuration for ranking.
     */
    rankingConfig?: pulumi.Input<inputs.VirtualIndexRankingConfig>;
    timeouts?: pulumi.Input<inputs.VirtualIndexTimeouts>;
    /**
     * The configuration for typos in index setting.
     */
    typosConfig?: pulumi.Input<inputs.VirtualIndexTyposConfig>;
    virtualIndexId?: pulumi.Input<string>;
}
