config:
  core:project: news-research-dev
  core:region: us-central1
  core:kmsLocation: us
  core:archiveLocation: US
  core:archiveTTL: 30
  core:githubOrg: ajaremko
  core:githubRepo: news-research
  ingestion:project: news-research-dev
  ingestion:region: us-central1
  ingestion:ingestorTag: 32-02.03.26-dev-41dc135
