config:
  core:project: news-research-core
  core:region: us-central1
  core:tag: shared
  core:kmsLocation: us
  core:archiveLocation: US
  core:archiveTTL: 30
  core:githubOrg: ajaremko
  core:githubRepo: news-research
  ingestion:project: news-research-ingestion
  ingestion:region: us-central1
  ingestion:tag: ingestion
