config:
  shared:project: news-research-dev
  shared:region: us-central1
  shared:tag: shared
  shared:kmsLocation: us
  shared:archiveLocation: US
  shared:archiveTTL: 30
  shared:githubOrg: ajaremko
  shared:githubRepo: news-research
  ingestion:project: news-research-dev
  ingestion:region: us-central1
  ingestion:tag: ingestion
