config:
  core:project: news-research-dev
  core:region: us-central1
  core:kmsLocation: us
  core:archiveLocation: US
  core:archiveTTL: 1
  core:githubOrg: ajaremko
  core:githubRepo: news-research
  ingestion:project: news-research-dev
  ingestion:region: us-central1
  ingestion:ingestorTag: dev-46
  ingestion:ingestorSchedule: '0 */4 * * *'
