import torch
import torch.nn as nn
from transformers import BertTokenizer, BertModel
import spacy
import en_core_web_sm


# 1. Initialize tools
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
nlp = en_core_web_sm.load()

# 2. Define custom POS vocabulary and mapping
pos_list = ['PAD', 'NOUN', 'VERB', 'ADJ', 'ADV',
            'DET', 'PRON', 'ADP', 'CONJ', 'PRT', 'NUM', 'OTH']
pos2idx = {tag: idx for idx, tag in enumerate(pos_list)}


def prepare_text(text):
    # Load the English NLP model
    nlp = spacy.load("en_core_web_sm")

    # Process the text
    doc = nlp(text)

    # Extract POS tags
    pos_tags = [(token.text, token.pos_) for token in doc]

    doc = nlp(text)

    # 3. Align word-level POS tags with BERT subword tokens
    input_ids = []
    pos_ids = []

    for word in doc:
        subwords = tokenizer.tokenize(word.text)
        subword_ids = tokenizer.convert_tokens_to_ids(subwords)

        input_ids.extend(subword_ids)
        # Assign the same POS tag index to all subwords generated by this word
        tag_idx = pos2idx.get(word.pos_, pos2idx['OTH'])
        pos_ids.extend([tag_idx] * len(subwords))

    # Convert to PyTorch Tensors
    input_ids_tensor = torch.tensor([input_ids])  # Shape: (1, seq_len)
    pos_ids_tensor = torch.tensor([pos_ids])     # Shape: (1, seq_len)

    return input_ids_tensor, pos_ids_tensor


class BertWithPOSEmbeddings(nn.Module):
    def __init__(self, num_pos_tags, pos_dim=768):
        super().__init__()
        self.bert = BertModel.from_pretrained('bert-base-uncased')

        # pos_dim must match BERT's hidden size (768) to sum them up
        self.pos_embeddings = nn.Embedding(num_pos_tags, pos_dim)

        # Initialize weights gently
        nn.init.normal_(self.pos_embeddings.weight, mean=0, std=0.02)

    def forward(self, input_ids, pos_ids):
        # Pass input through BERT's base embedding layer (Token + Position + Segment)
        base_embeddings = self.bert.embeddings(input_ids=input_ids)

        # Get POS embeddings
        pos_embeds = self.pos_embeddings(pos_ids)

        # Element-wise addition (just like BERT adds position and segment vectors)
        final_embeddings = base_embeddings + pos_embeds

        # Forward pass through the rest of the BERT Encoder transformer layers
        encoder_outputs = self.bert.encoder(final_embeddings)

        # Return sequence output (last hidden states)
        return encoder_outputs.last_hidden_state


# Execution
pos_list = list(pos2idx.keys())
model = BertWithPOSEmbeddings(num_pos_tags=len(pos_list))


def extract_embeddings(text):
    input_ids_tensor, pos_ids_tensor = prepare_text(text)
    with torch.no_grad():
        embeddings = model(input_ids_tensor, pos_ids_tensor)
    return embeddings
