config:
  core:project: news-research-dev
  core:region: us-central1
  core:kmsLocation: us-central1
  core:githubOrg: ajaremko
  core:githubRepo: news-research
  core:workloadIdentityPoolId: shared-identity-pool-05

  analysis:project: news-research-dev
  analysis:region: us-central1
  analysis:tableDeletionProtection: false
  analysis:retainDatasetsOnDelete: false

  ingestion:project: news-research-dev
  ingestion:region: us-central1
  ingestion:archiveLocation: US
  ingestion:tag: dev-264
  ingestion:ingestorSchedule: '0 */4 * * *'
  ingestion:extractorSchedule: '0 */12 * * *'
  ingestion:logLevel: debug
  ingestion:logRetentionDays: 1
  ingestion:batchRetentionDays: 2
  ingestion:eventLogRetentionDays: 7
  ingestion:deadletterRetentionDays: 7
  ingestion:forceDestroyStorage: true
  ingestion:retainStorageOnDelete: true

  research:project: news-research-dev
  research:region: us-central1
