// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetIndexAdvancedConfig {
    attributeCriteriaComputedByMinProximity: boolean;
    attributeForDistinct: string;
    distinct: number;
    maxFacetHits: number;
    minProximity: number;
    replaceSynonymsInHighlight: boolean;
    responseFields: string[];
}

export interface GetIndexAttributesConfig {
    attributesForFacetings: string[];
    attributesToRetrieves: string[];
    searchableAttributes: string[];
    unretrievableAttributes: string[];
}

export interface GetIndexFacetingConfig {
    maxValuesPerFacet: number;
    sortFacetValuesBy: string;
}

export interface GetIndexHighlightAndSnippetConfig {
    attributesToHighlights: string[];
    attributesToSnippets: string[];
    highlightPostTag: string;
    highlightPreTag: string;
    restrictHighlightAndSnippetArrays: boolean;
    snippetEllipsisText: string;
}

export interface GetIndexLanguagesConfig {
    attributesToTransliterates: string[];
    camelCaseAttributes: string[];
    customNormalization: {[key: string]: string};
    decompoundQuery: boolean;
    decompoundedAttributes: outputs.GetIndexLanguagesConfigDecompoundedAttribute[];
    ignorePlurals: boolean;
    ignorePluralsFors: string[];
    indexLanguages: string[];
    keepDiacriticsOnCharacters: string;
    queryLanguages: string[];
    removeStopWords: boolean;
    removeStopWordsFors: string[];
}

export interface GetIndexLanguagesConfigDecompoundedAttribute {
    attributes: string[];
    language: string;
}

export interface GetIndexPaginationConfig {
    /**
     * The number of hits per page.
     */
    hitsPerPage: number;
    /**
     * The maximum number of hits accessible via pagination
     */
    paginationLimitedTo: number;
}

export interface GetIndexPerformanceConfig {
    allowCompressionOfIntegerArray: boolean;
    numericAttributesForFilterings: string[];
}

export interface GetIndexQueryStrategyConfig {
    advancedSyntax: boolean;
    advancedSyntaxFeatures: string[];
    alternativesAsExacts: string[];
    disableExactOnAttributes: string[];
    disablePrefixOnAttributes: string[];
    exactOnSingleWordQuery: string;
    optionalWords: string[];
    queryType: string;
    removeWordsIfNoResults: string;
}

export interface GetIndexRankingConfig {
    customRankings: string[];
    rankings: string[];
    relevancyStrictness: number;
    replicas: string[];
}

export interface GetIndexTyposConfig {
    allowTyposOnNumericTokens: boolean;
    disableTypoToleranceOnAttributes: string[];
    disableTypoToleranceOnWords: string[];
    minWordSizeFor1Typo: number;
    minWordSizeFor2Typos: number;
    separatorsToIndex: string;
    typoTolerance: string;
}

export interface GetVirtualIndexAdvancedConfig {
    attributeCriteriaComputedByMinProximity: boolean;
    attributeForDistinct: string;
    distinct: number;
    maxFacetHits: number;
    minProximity: number;
    replaceSynonymsInHighlight: boolean;
    responseFields: string[];
}

export interface GetVirtualIndexAttributesConfig {
    attributesForFacetings: string[];
    attributesToRetrieves: string[];
    searchableAttributes: string[];
    unretrievableAttributes: string[];
}

export interface GetVirtualIndexFacetingConfig {
    maxValuesPerFacet: number;
    sortFacetValuesBy: string;
}

export interface GetVirtualIndexHighlightAndSnippetConfig {
    attributesToHighlights: string[];
    attributesToSnippets: string[];
    highlightPostTag: string;
    highlightPreTag: string;
    restrictHighlightAndSnippetArrays: boolean;
    snippetEllipsisText: string;
}

export interface GetVirtualIndexLanguagesConfig {
    attributesToTransliterates: string[];
    camelCaseAttributes: string[];
    customNormalization: {[key: string]: string};
    decompoundQuery: boolean;
    decompoundedAttributes: outputs.GetVirtualIndexLanguagesConfigDecompoundedAttribute[];
    ignorePlurals: boolean;
    ignorePluralsFors: string[];
    indexLanguages: string[];
    keepDiacriticsOnCharacters: string;
    queryLanguages: string[];
    removeStopWords: boolean;
    removeStopWordsFors: string[];
}

export interface GetVirtualIndexLanguagesConfigDecompoundedAttribute {
    attributes: string[];
    language: string;
}

export interface GetVirtualIndexPaginationConfig {
    /**
     * The number of hits per page.
     */
    hitsPerPage: number;
    /**
     * The maximum number of hits accessible via pagination
     */
    paginationLimitedTo: number;
}

export interface GetVirtualIndexPerformanceConfig {
    allowCompressionOfIntegerArray: boolean;
    numericAttributesForFilterings: string[];
}

export interface GetVirtualIndexQueryStrategyConfig {
    advancedSyntax: boolean;
    advancedSyntaxFeatures: string[];
    alternativesAsExacts: string[];
    disableExactOnAttributes: string[];
    disablePrefixOnAttributes: string[];
    exactOnSingleWordQuery: string;
    optionalWords: string[];
    queryType: string;
    removeWordsIfNoResults: string;
}

export interface GetVirtualIndexRankingConfig {
    customRankings: string[];
    rankings: string[];
    relevancyStrictness: number;
}

export interface GetVirtualIndexTyposConfig {
    allowTyposOnNumericTokens: boolean;
    disableTypoToleranceOnAttributes: string[];
    disableTypoToleranceOnWords: string[];
    minWordSizeFor1Typo: number;
    minWordSizeFor2Typos: number;
    separatorsToIndex: string;
    typoTolerance: string;
}

export interface IndexAdvancedConfig {
    /**
     * When attribute is ranked above proximity in your ranking formula, proximity is used to select which searchable attribute is matched in the **attribute ranking stage**.
     */
    attributeCriteriaComputedByMinProximity?: boolean;
    /**
     * Name of the de-duplication attribute to be used with the <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> feature.
     */
    attributeForDistinct?: string;
    /**
     * Whether to enable de-duplication or grouping of results.
     * - When set to <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>, you disable de-duplication and grouping.
     * - When set to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>, you enable **de-duplication**, in which only the most relevant result is returned for all records that have the same value in the distinct attribute. This is similar to the SQL <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> keyword.
     * if <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> is set to 1 (de-duplication):
     * - When set to `N (where N > 1)`, you enable grouping, in which most N hits will be returned with the same value for the distinct attribute.
     * then the N most relevant episodes for every show are kept, with similar consequences.
     */
    distinct?: number;
    /**
     * Maximum number of facet hits to return during a search for facet values.
     */
    maxFacetHits?: number;
    /**
     * Precision of the <span pulumi-lang-nodejs="`proximity`" pulumi-lang-dotnet="`Proximity`" pulumi-lang-go="`proximity`" pulumi-lang-python="`proximity`" pulumi-lang-yaml="`proximity`" pulumi-lang-java="`proximity`" pulumi-lang-hcl="`proximity`">`proximity`</span> ranking criterion.
     */
    minProximity?: number;
    /**
     * Whether to highlight and snippet the original word that matches the synonym or the synonym itself.
     */
    replaceSynonymsInHighlight?: boolean;
    /**
     * The fields the response will contain. Applies to search and browse queries.
     * This parameter is mainly intended to **limit the response size.** For example, in complex queries, echoing of request parameters in the response’s params field can be undesirable.
     */
    responseFields?: string[];
}

export interface IndexAttributesConfig {
    /**
     * The complete list of attributes that will be used for faceting.
     */
    attributesForFacetings?: string[];
    /**
     * List of attributes to be retrieved at query time.
     */
    attributesToRetrieves?: string[];
    /**
     * The complete list of attributes used for searching.
     */
    searchableAttributes?: string[];
    /**
     * List of attributes that cannot be retrieved at query time.
     */
    unretrievableAttributes?: string[];
}

export interface IndexFacetingConfig {
    /**
     * Maximum number of facet values to return for each facet during a regular search.
     */
    maxValuesPerFacet?: number;
    /**
     * Parameter to controls how the facet values are sorted within each faceted attribute.
     */
    sortFacetValuesBy?: string;
}

export interface IndexHighlightAndSnippetConfig {
    /**
     * List of attributes to highlight.
     */
    attributesToHighlights: string[];
    /**
     * List of attributes to snippet, with an optional maximum number of words to snippet.
     */
    attributesToSnippets: string[];
    /**
     * The HTML string to insert after the highlighted parts in all highlight and snippet results.
     */
    highlightPostTag?: string;
    /**
     * The HTML string to insert before the highlighted parts in all highlight and snippet results.
     */
    highlightPreTag?: string;
    /**
     * Restrict highlighting and snippeting to items that matched the query.
     */
    restrictHighlightAndSnippetArrays?: boolean;
    /**
     * String used as an ellipsis indicator when a snippet is truncated.
     */
    snippetEllipsisText?: string;
}

export interface IndexLanguagesConfig {
    /**
     * List of attributes to apply transliteration
     */
    attributesToTransliterates: string[];
    /**
     * List of attributes on which to do a decomposition of camel case words.
     */
    camelCaseAttributes?: string[];
    /**
     * Custom normalization which overrides the engine’s default normalization
     */
    customNormalization?: {[key: string]: string};
    /**
     * Whether to split compound words into their composing atoms in the query.
     */
    decompoundQuery?: boolean;
    /**
     * List of attributes to apply word segmentation, also known as decompounding.
     */
    decompoundedAttributes?: outputs.IndexLanguagesConfigDecompoundedAttribute[];
    /**
     * Whether to treat singular, plurals, and other forms of declensions as matching terms.
     */
    ignorePlurals?: boolean;
    /**
     * Whether to treat singular, plurals, and other forms of declensions as matching terms in target languages.
     * List of supported languages are listed on http://nhttps//www.algolia.com/doc/api-reference/api-parameters/ignorePlurals/#usage-notes
     */
    ignorePluralsFors?: string[];
    /**
     * List of languages at the index level for language-specific processing such as tokenization and normalization.
     */
    indexLanguages?: string[];
    /**
     * List of characters that the engine shouldn’t automatically normalize.
     */
    keepDiacriticsOnCharacters?: string;
    /**
     * List of languages to be used by language-specific settings and functionalities such as ignorePlurals, removeStopWords, and CJK word-detection.
     */
    queryLanguages?: string[];
    /**
     * Whether to removes stop (common) words from the query before executing it.
     */
    removeStopWords?: boolean;
    /**
     * List of languages to removes stop (common) words from the query before executing it.
     */
    removeStopWordsFors?: string[];
}

export interface IndexLanguagesConfigDecompoundedAttribute {
    attributes: string[];
    language: string;
}

export interface IndexPaginationConfig {
    /**
     * The number of hits per page.
     */
    hitsPerPage?: number;
    /**
     * The maximum number of hits accessible via pagination
     */
    paginationLimitedTo?: number;
}

export interface IndexPerformanceConfig {
    /**
     * Whether to enable compression of large integer arrays.
     */
    allowCompressionOfIntegerArray?: boolean;
    /**
     * List of numeric attributes that can be used as numerical filters.
     */
    numericAttributesForFilterings?: string[];
}

export interface IndexQueryStrategyConfig {
    /**
     * Whether to enable the advanced query syntax.
     */
    advancedSyntax?: boolean;
    /**
     * Advanced syntax features to be activated when ‘advancedSyntax’ is enabled
     */
    advancedSyntaxFeatures?: string[];
    /**
     * List of alternatives that should be considered an exact match by the exact ranking criterion.
     */
    alternativesAsExacts?: string[];
    /**
     * List of attributes on which you want to disable the exact ranking criterion.
     */
    disableExactOnAttributes?: string[];
    /**
     * List of attributes on which you want to disable prefix matching.
     */
    disablePrefixOnAttributes?: string[];
    /**
     * Controls how the exact ranking criterion is computed when the query contains only one word.
     */
    exactOnSingleWordQuery?: string;
    /**
     * A list of words that should be considered as optional when found in the query.
     */
    optionalWords?: string[];
    /**
     * Query type to control if and how query words are interpreted as prefixes.
     */
    queryType?: string;
    /**
     * Strategy to remove words from the query when it doesn’t match any hits.
     */
    removeWordsIfNoResults?: string;
}

export interface IndexRankingConfig {
    /**
     * List of attributes for custom ranking criterion.
     */
    customRankings?: string[];
    /**
     * List of ranking criteria.
     */
    rankings?: string[];
    /**
     * Relevancy threshold below which less relevant results aren’t included in the results
     */
    relevancyStrictness?: number;
}

export interface IndexTimeouts {
    default?: string;
}

export interface IndexTyposConfig {
    /**
     * Whether to allow typos on numbers (“numeric tokens”) in the query str
     */
    allowTyposOnNumericTokens?: boolean;
    /**
     * List of attributes on which you want to disable typo tolerance.
     */
    disableTypoToleranceOnAttributes?: string[];
    /**
     * List of words on which typo tolerance will be disabled.
     */
    disableTypoToleranceOnWords?: string[];
    /**
     * Minimum number of characters a word in the query string must contain to accept matches with 1 typo.
     */
    minWordSizeFor1Typo?: number;
    /**
     * Minimum number of characters a word in the query string must contain to accept matches with 2 typos.
     */
    minWordSizeFor2Typos?: number;
    /**
     * Separators (punctuation characters) to index. By default, separators are not indexed.
     */
    separatorsToIndex?: string;
    /**
     * Whether typo tolerance is enabled and how it is applied
     */
    typoTolerance?: string;
}

export interface QuerySuggestionsSourceIndex {
    /**
     * A list of analytics tags to filter the popular searches per tag.
     */
    analyticsTags?: string[];
    /**
     * A list of external indices to use to generate custom Query Suggestions.
     */
    externals?: string[];
    /**
     * A list of facets to define as categories for the query suggestions.
     */
    facets?: outputs.QuerySuggestionsSourceIndexFacet[];
    /**
     * List of facet attributes used to generate Query Suggestions. The resulting suggestions are every combination of the facets in the nested list 
     * (e.g., (facetA and facetB) and facetC).
     * ```
     * [
     *   ["facetA", "facetB"],
     *   ["facetC"]
     * ]
     * ```
     */
    generates?: string[][];
    /**
     * Index name to target.
     */
    indexName: string;
    /**
     * Minimum number of hits (e.g., matching records in the source index) to generate a suggestions.
     */
    minHits: number;
    /**
     * Minimum number of required letters for a suggestion to remain.
     */
    minLetters: number;
}

export interface QuerySuggestionsSourceIndexFacet {
    /**
     * How many of the top categories to show
     */
    amount: number;
    /**
     * Category attribute in your index
     */
    attribute: string;
}

export interface RuleCondition {
    /**
     * Whether the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span> matches on plurals, synonyms, and typos.
     *
     * This parameter goes hand in hand with the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span>  parameter. If the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span> is “shoe” and <span pulumi-lang-nodejs="`alternatives`" pulumi-lang-dotnet="`Alternatives`" pulumi-lang-go="`alternatives`" pulumi-lang-python="`alternatives`" pulumi-lang-yaml="`alternatives`" pulumi-lang-java="`alternatives`" pulumi-lang-hcl="`alternatives`">`alternatives`</span> is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span> matches on “shoes”, as well as synonyms and typos of “shoe”.
     */
    alternatives?: boolean;
    /**
     * Whether the pattern parameter must match the beginning or the end of the query string, or both, or none.
     * Possible values are <span pulumi-lang-nodejs="`is`" pulumi-lang-dotnet="`Is`" pulumi-lang-go="`is`" pulumi-lang-python="`is`" pulumi-lang-yaml="`is`" pulumi-lang-java="`is`" pulumi-lang-hcl="`is`">`is`</span>, `startsWith`, `endsWith` and <span pulumi-lang-nodejs="`contains`" pulumi-lang-dotnet="`Contains`" pulumi-lang-go="`contains`" pulumi-lang-python="`contains`" pulumi-lang-yaml="`contains`" pulumi-lang-java="`contains`" pulumi-lang-hcl="`contains`">`contains`</span>.
     * This parameter goes hand in hand with the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span> parameter. If you’re creating a Rule that depends on a specific query, you must specify the <span pulumi-lang-nodejs="`pattern`" pulumi-lang-dotnet="`Pattern`" pulumi-lang-go="`pattern`" pulumi-lang-python="`pattern`" pulumi-lang-yaml="`pattern`" pulumi-lang-java="`pattern`" pulumi-lang-hcl="`pattern`">`pattern`</span> and <span pulumi-lang-nodejs="`anchoring`" pulumi-lang-dotnet="`Anchoring`" pulumi-lang-go="`anchoring`" pulumi-lang-python="`anchoring`" pulumi-lang-yaml="`anchoring`" pulumi-lang-java="`anchoring`" pulumi-lang-hcl="`anchoring`">`anchoring`</span>.
     *
     * Otherwise, you can omit both.
     */
    anchoring?: string;
    /**
     * Rule context (format: `[A-Za-z0-9_-]+`). When specified, the Rule is only applied when the same context is specified at query time (using the `ruleContexts` parameter). When absent, the Rule is generic and always applies (provided that its other conditions are met, of course).
     */
    context?: string;
    /**
     * Query pattern syntax.
     * Query patterns are expressed as a string with a specific syntax. A pattern is a sequence of tokens, which can be either:
     *
     * - Facet value placeholder: `{facet:$facet_name}`. Example: `{facet:brand}`.
     * - Literal: the world itself. Example: Algolia.
     * Special characters (`*`, `{`, `}`, `:` and `\`) must be escaped by preceding them with a backslash (\) if they are to be treated as literals.
     *
     * This parameter goes hand in hand with the <span pulumi-lang-nodejs="`anchoring`" pulumi-lang-dotnet="`Anchoring`" pulumi-lang-go="`anchoring`" pulumi-lang-python="`anchoring`" pulumi-lang-yaml="`anchoring`" pulumi-lang-java="`anchoring`" pulumi-lang-hcl="`anchoring`">`anchoring`</span> parameter. If you’re creating a Rule that depends on a specific query, you must specify the pattern and anchoring. The empty `""` pattern is only allowed when <span pulumi-lang-nodejs="`anchoring`" pulumi-lang-dotnet="`Anchoring`" pulumi-lang-go="`anchoring`" pulumi-lang-python="`anchoring`" pulumi-lang-yaml="`anchoring`" pulumi-lang-java="`anchoring`" pulumi-lang-hcl="`anchoring`">`anchoring`</span> is set to <span pulumi-lang-nodejs="`is`" pulumi-lang-dotnet="`Is`" pulumi-lang-go="`is`" pulumi-lang-python="`is`" pulumi-lang-yaml="`is`" pulumi-lang-java="`is`" pulumi-lang-hcl="`is`">`is`</span>.
     *
     * Otherwise, you can omit both.
     */
    pattern?: string;
}

export interface RuleConsequence {
    /**
     * List of object IDs to hide from hits.
     */
    hides?: string[];
    /**
     * **Deprecated:** Use <span pulumi-lang-nodejs="`paramsJson`" pulumi-lang-dotnet="`ParamsJson`" pulumi-lang-go="`paramsJson`" pulumi-lang-python="`params_json`" pulumi-lang-yaml="`paramsJson`" pulumi-lang-java="`paramsJson`" pulumi-lang-hcl="`params_json`">`paramsJson`</span> instead. Additional search parameters. Any valid search parameter is allowed. Specific treatment is applied to these fields: <span pulumi-lang-nodejs="`query`" pulumi-lang-dotnet="`Query`" pulumi-lang-go="`query`" pulumi-lang-python="`query`" pulumi-lang-yaml="`query`" pulumi-lang-java="`query`" pulumi-lang-hcl="`query`">`query`</span>, `automaticFacetFilters`, `automaticOptionalFacetFilters`.
     *
     * @deprecated Deprecated
     */
    params?: outputs.RuleConsequenceParams;
    /**
     * Additional search parameters in JSON format. Any valid search parameter is allowed. Specific treatment is applied to these fields: <span pulumi-lang-nodejs="`query`" pulumi-lang-dotnet="`Query`" pulumi-lang-go="`query`" pulumi-lang-python="`query`" pulumi-lang-yaml="`query`" pulumi-lang-java="`query`" pulumi-lang-hcl="`query`">`query`</span>, `automaticFacetFilters`, `automaticOptionalFacetFilters`.
     */
    paramsJson?: string;
    /**
     * Objects to promote as hits.
     */
    promotes?: outputs.RuleConsequencePromote[];
    /**
     * Custom JSON formatted string that will be appended to the userData array in the response. This object is not interpreted by the API. It is limited to 1kB of minified JSON.
     */
    userData?: string;
}

export interface RuleConsequenceParams {
    /**
     * Names of facets to which automatic filtering must be applied; they must match the facet name of a facet value placeholder in the query pattern.
     */
    automaticFacetFilters?: outputs.RuleConsequenceParamsAutomaticFacetFilter[];
    /**
     * Same syntax as <span pulumi-lang-nodejs="`automaticFacetFilters`" pulumi-lang-dotnet="`AutomaticFacetFilters`" pulumi-lang-go="`automaticFacetFilters`" pulumi-lang-python="`automatic_facet_filters`" pulumi-lang-yaml="`automaticFacetFilters`" pulumi-lang-java="`automaticFacetFilters`" pulumi-lang-hcl="`automatic_facet_filters`">`automaticFacetFilters`</span>, but the engine treats the filters as optional. Behaves like [optionalFilters](https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/).
     */
    automaticOptionalFacetFilters?: outputs.RuleConsequenceParamsAutomaticOptionalFacetFilter[];
    /**
     * It describes incremental edits to be made to the query string. Either one of <span pulumi-lang-nodejs="`query`" pulumi-lang-dotnet="`Query`" pulumi-lang-go="`query`" pulumi-lang-python="`query`" pulumi-lang-yaml="`query`" pulumi-lang-java="`query`" pulumi-lang-hcl="`query`">`query`</span> or <span pulumi-lang-nodejs="`objectQuery`" pulumi-lang-dotnet="`ObjectQuery`" pulumi-lang-go="`objectQuery`" pulumi-lang-python="`object_query`" pulumi-lang-yaml="`objectQuery`" pulumi-lang-java="`objectQuery`" pulumi-lang-hcl="`object_query`">`objectQuery`</span> can be set.
     */
    objectQueries?: outputs.RuleConsequenceParamsObjectQuery[];
    /**
     * It replaces the entire query string. Either one of <span pulumi-lang-nodejs="`query`" pulumi-lang-dotnet="`Query`" pulumi-lang-go="`query`" pulumi-lang-python="`query`" pulumi-lang-yaml="`query`" pulumi-lang-java="`query`" pulumi-lang-hcl="`query`">`query`</span> or <span pulumi-lang-nodejs="`objectQuery`" pulumi-lang-dotnet="`ObjectQuery`" pulumi-lang-go="`objectQuery`" pulumi-lang-python="`object_query`" pulumi-lang-yaml="`objectQuery`" pulumi-lang-java="`objectQuery`" pulumi-lang-hcl="`object_query`">`objectQuery`</span> can be set.
     */
    query?: string;
}

export interface RuleConsequenceParamsAutomaticFacetFilter {
    /**
     * Whether the filter is disjunctive (true) or conjunctive (false). If the filter applies multiple times, e.g. because the query string contains multiple values of the same facet, the multiple occurrences are combined with an `AND` operator by default (conjunctive mode). If the filter is specified as disjunctive, however, multiple occurrences are combined with an `OR` operator instead.
     */
    disjunctive?: boolean;
    /**
     * Attribute to filter on. This must match a facet placeholder in the Rule’s pattern.
     */
    facet: string;
    /**
     * Score for the filter. Typically used for optional or disjunctive filters.
     */
    score?: number;
}

export interface RuleConsequenceParamsAutomaticOptionalFacetFilter {
    /**
     * Whether the filter is disjunctive (true) or conjunctive (false). If the filter applies multiple times, e.g. because the query string contains multiple values of the same facet, the multiple occurrences are combined with an `AND` operator by default (conjunctive mode). If the filter is specified as disjunctive, however, multiple occurrences are combined with an `OR` operator instead.
     */
    disjunctive?: boolean;
    /**
     * Attribute to filter on. This must match a facet placeholder in the Rule’s pattern.
     */
    facet: string;
    /**
     * Score for the filter. Typically used for optional or disjunctive filters.
     */
    score?: number;
}

export interface RuleConsequenceParamsObjectQuery {
    /**
     * Text or patterns to remove from the query string.
     */
    delete: string;
    /**
     * Text that should be inserted in place of the removed text inside the query string.
     */
    insert?: string;
    /**
     * Type of edit. Must be one of:
     * 	- <span pulumi-lang-nodejs="`remove`" pulumi-lang-dotnet="`Remove`" pulumi-lang-go="`remove`" pulumi-lang-python="`remove`" pulumi-lang-yaml="`remove`" pulumi-lang-java="`remove`" pulumi-lang-hcl="`remove`">`remove`</span>: when you want to delete some text and not replace it with anything
     * 	- <span pulumi-lang-nodejs="`replace`" pulumi-lang-dotnet="`Replace`" pulumi-lang-go="`replace`" pulumi-lang-python="`replace`" pulumi-lang-yaml="`replace`" pulumi-lang-java="`replace`" pulumi-lang-hcl="`replace`">`replace`</span>: when you want to delete some text and replace it with something else
     */
    type: string;
}

export interface RuleConsequencePromote {
    objectIds: string[];
    /**
     * The position to promote the object(s) to (zero-based). If you pass <span pulumi-lang-nodejs="`objectIds`" pulumi-lang-dotnet="`ObjectIds`" pulumi-lang-go="`objectIds`" pulumi-lang-python="`object_ids`" pulumi-lang-yaml="`objectIds`" pulumi-lang-java="`objectIds`" pulumi-lang-hcl="`object_ids`">`objectIds`</span>, we place the objects at this position as a group. For example, if you pass four <span pulumi-lang-nodejs="`objectIds`" pulumi-lang-dotnet="`ObjectIds`" pulumi-lang-go="`objectIds`" pulumi-lang-python="`object_ids`" pulumi-lang-yaml="`objectIds`" pulumi-lang-java="`objectIds`" pulumi-lang-hcl="`object_ids`">`objectIds`</span> to position <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>, the objects take the first four positions.
     */
    position: number;
}

export interface RuleValidity {
    /**
     * Lower bound of the time range. RFC3339 format.
     */
    from: string;
    /**
     * Upper bound of the time range. RFC3339 format.
     */
    until: string;
}

export interface SynonymsSynonym {
    /**
     * List of corrections of the <span pulumi-lang-nodejs="`word`" pulumi-lang-dotnet="`Word`" pulumi-lang-go="`word`" pulumi-lang-python="`word`" pulumi-lang-yaml="`word`" pulumi-lang-java="`word`" pulumi-lang-hcl="`word`">`word`</span>. Required if type=`altCorrection1` or type=`altCorrection2`
     */
    corrections?: string[];
    /**
     * Defines the synonym. A word or expression, used as the basis for the array of synonyms. Required if type=`oneWaySynonym`.
     */
    input?: string;
    /**
     * Unique identifier for the synonym.It can contain any character, and be of unlimited length.
     */
    objectId: string;
    /**
     * Single word, used as the basis for the below array of replacements.  Required if type=<span pulumi-lang-nodejs="`placeholder`" pulumi-lang-dotnet="`Placeholder`" pulumi-lang-go="`placeholder`" pulumi-lang-python="`placeholder`" pulumi-lang-yaml="`placeholder`" pulumi-lang-java="`placeholder`" pulumi-lang-hcl="`placeholder`">`placeholder`</span>
     */
    placeholder?: string;
    /**
     * List of replacements of the placeholder. Required if type=<span pulumi-lang-nodejs="`placeholder`" pulumi-lang-dotnet="`Placeholder`" pulumi-lang-go="`placeholder`" pulumi-lang-python="`placeholder`" pulumi-lang-yaml="`placeholder`" pulumi-lang-java="`placeholder`" pulumi-lang-hcl="`placeholder`">`placeholder`</span>
     */
    replacements?: string[];
    /**
     * List of synonyms (up to `20 for type <span pulumi-lang-nodejs="`synonym`" pulumi-lang-dotnet="`Synonym`" pulumi-lang-go="`synonym`" pulumi-lang-python="`synonym`" pulumi-lang-yaml="`synonym`" pulumi-lang-java="`synonym`" pulumi-lang-hcl="`synonym`">`synonym`</span> and 100 for type `oneWaySynonym`). Required if type=<span pulumi-lang-nodejs="`synonym`" pulumi-lang-dotnet="`Synonym`" pulumi-lang-go="`synonym`" pulumi-lang-python="`synonym`" pulumi-lang-yaml="`synonym`" pulumi-lang-java="`synonym`" pulumi-lang-hcl="`synonym`">`synonym`</span> or type=`oneWaySynonym`.
     */
    synonyms?: string[];
    /**
     * The type of the synonym. Possible values are <span pulumi-lang-nodejs="`synonym`" pulumi-lang-dotnet="`Synonym`" pulumi-lang-go="`synonym`" pulumi-lang-python="`synonym`" pulumi-lang-yaml="`synonym`" pulumi-lang-java="`synonym`" pulumi-lang-hcl="`synonym`">`synonym`</span>, `oneWaySynonym`, `altCorrection1`, `altCorrection2` and <span pulumi-lang-nodejs="`placeholder`" pulumi-lang-dotnet="`Placeholder`" pulumi-lang-go="`placeholder`" pulumi-lang-python="`placeholder`" pulumi-lang-yaml="`placeholder`" pulumi-lang-java="`placeholder`" pulumi-lang-hcl="`placeholder`">`placeholder`</span>.
     */
    type: string;
    /**
     * Single word, used as the basis for the below array of corrections. Required if type=`altCorrection1` or type=`altCorrection2`
     */
    word?: string;
}

export interface VirtualIndexAdvancedConfig {
    /**
     * When attribute is ranked above proximity in your ranking formula, proximity is used to select which searchable attribute is matched in the **attribute ranking stage**.
     */
    attributeCriteriaComputedByMinProximity?: boolean;
    /**
     * Name of the de-duplication attribute to be used with the <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> feature.
     */
    attributeForDistinct: string;
    /**
     * Whether to enable de-duplication or grouping of results.
     * - When set to <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span>, you disable de-duplication and grouping.
     * - When set to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>, you enable **de-duplication**, in which only the most relevant result is returned for all records that have the same value in the distinct attribute. This is similar to the SQL <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> keyword.
     * if <span pulumi-lang-nodejs="`distinct`" pulumi-lang-dotnet="`Distinct`" pulumi-lang-go="`distinct`" pulumi-lang-python="`distinct`" pulumi-lang-yaml="`distinct`" pulumi-lang-java="`distinct`" pulumi-lang-hcl="`distinct`">`distinct`</span> is set to 1 (de-duplication):
     * - When set to `N (where N > 1)`, you enable grouping, in which most N hits will be returned with the same value for the distinct attribute.
     * then the N most relevant episodes for every show are kept, with similar consequences.
     */
    distinct?: number;
    /**
     * Maximum number of facet hits to return during a search for facet values.
     */
    maxFacetHits?: number;
    /**
     * Precision of the <span pulumi-lang-nodejs="`proximity`" pulumi-lang-dotnet="`Proximity`" pulumi-lang-go="`proximity`" pulumi-lang-python="`proximity`" pulumi-lang-yaml="`proximity`" pulumi-lang-java="`proximity`" pulumi-lang-hcl="`proximity`">`proximity`</span> ranking criterion.
     */
    minProximity?: number;
    /**
     * Whether to highlight and snippet the original word that matches the synonym or the synonym itself.
     */
    replaceSynonymsInHighlight?: boolean;
    /**
     * The fields the response will contain. Applies to search and browse queries.
     * This parameter is mainly intended to **limit the response size.** For example, in complex queries, echoing of request parameters in the response’s params field can be undesirable.
     */
    responseFields?: string[];
}

export interface VirtualIndexAttributesConfig {
    /**
     * The complete list of attributes that will be used for faceting.
     */
    attributesForFacetings: string[];
    /**
     * List of attributes to be retrieved at query time.
     */
    attributesToRetrieves?: string[];
    /**
     * The complete list of attributes used for searching.
     */
    searchableAttributes: string[];
    /**
     * List of attributes that cannot be retrieved at query time.
     */
    unretrievableAttributes?: string[];
}

export interface VirtualIndexFacetingConfig {
    /**
     * Maximum number of facet values to return for each facet during a regular search.
     */
    maxValuesPerFacet?: number;
    /**
     * Parameter to controls how the facet values are sorted within each faceted attribute.
     */
    sortFacetValuesBy?: string;
}

export interface VirtualIndexHighlightAndSnippetConfig {
    /**
     * List of attributes to highlight.
     */
    attributesToHighlights: string[];
    /**
     * List of attributes to snippet, with an optional maximum number of words to snippet.
     */
    attributesToSnippets: string[];
    /**
     * The HTML string to insert after the highlighted parts in all highlight and snippet results.
     */
    highlightPostTag?: string;
    /**
     * The HTML string to insert before the highlighted parts in all highlight and snippet results.
     */
    highlightPreTag?: string;
    /**
     * Restrict highlighting and snippeting to items that matched the query.
     */
    restrictHighlightAndSnippetArrays?: boolean;
    /**
     * String used as an ellipsis indicator when a snippet is truncated.
     */
    snippetEllipsisText?: string;
}

export interface VirtualIndexLanguagesConfig {
    /**
     * List of attributes to apply transliteration
     */
    attributesToTransliterates: string[];
    /**
     * List of attributes on which to do a decomposition of camel case words.
     */
    camelCaseAttributes: string[];
    /**
     * Custom normalization which overrides the engine’s default normalization
     */
    customNormalization: {[key: string]: string};
    /**
     * Whether to split compound words into their composing atoms in the query.
     */
    decompoundQuery?: boolean;
    /**
     * List of attributes to apply word segmentation, also known as decompounding.
     */
    decompoundedAttributes: outputs.VirtualIndexLanguagesConfigDecompoundedAttribute[];
    /**
     * Whether to treat singular, plurals, and other forms of declensions as matching terms.
     */
    ignorePlurals?: boolean;
    /**
     * Whether to treat singular, plurals, and other forms of declensions as matching terms in target languages.
     * List of supported languages are listed on http://nhttps//www.algolia.com/doc/api-reference/api-parameters/ignorePlurals/#usage-notes
     */
    ignorePluralsFors?: string[];
    /**
     * List of languages at the index level for language-specific processing such as tokenization and normalization.
     */
    indexLanguages: string[];
    /**
     * List of characters that the engine shouldn’t automatically normalize.
     */
    keepDiacriticsOnCharacters: string;
    /**
     * List of languages to be used by language-specific settings and functionalities such as ignorePlurals, removeStopWords, and CJK word-detection.
     */
    queryLanguages?: string[];
    /**
     * Whether to removes stop (common) words from the query before executing it.
     */
    removeStopWords?: boolean;
    /**
     * List of languages to removes stop (common) words from the query before executing it.
     */
    removeStopWordsFors?: string[];
}

export interface VirtualIndexLanguagesConfigDecompoundedAttribute {
    attributes: string[];
    language: string;
}

export interface VirtualIndexPaginationConfig {
    /**
     * The number of hits per page.
     */
    hitsPerPage?: number;
    /**
     * The maximum number of hits accessible via pagination
     */
    paginationLimitedTo?: number;
}

export interface VirtualIndexPerformanceConfig {
    allowCompressionOfIntegerArray: boolean;
    numericAttributesForFilterings: string[];
}

export interface VirtualIndexQueryStrategyConfig {
    /**
     * Whether to enable the advanced query syntax.
     */
    advancedSyntax?: boolean;
    /**
     * Advanced syntax features to be activated when ‘advancedSyntax’ is enabled
     */
    advancedSyntaxFeatures?: string[];
    /**
     * List of alternatives that should be considered an exact match by the exact ranking criterion.
     */
    alternativesAsExacts?: string[];
    /**
     * List of attributes on which you want to disable the exact ranking criterion.
     */
    disableExactOnAttributes: string[];
    /**
     * List of attributes on which you want to disable prefix matching.
     */
    disablePrefixOnAttributes: string[];
    /**
     * Controls how the exact ranking criterion is computed when the query contains only one word.
     */
    exactOnSingleWordQuery?: string;
    /**
     * A list of words that should be considered as optional when found in the query.
     */
    optionalWords: string[];
    /**
     * Query type to control if and how query words are interpreted as prefixes.
     */
    queryType?: string;
    /**
     * Strategy to remove words from the query when it doesn’t match any hits.
     */
    removeWordsIfNoResults?: string;
}

export interface VirtualIndexRankingConfig {
    /**
     * List of attributes for custom ranking criterion.
     */
    customRankings?: string[];
    /**
     * List of ranking criteria.
     */
    rankings: string[];
    /**
     * Relevancy threshold below which less relevant results aren’t included in the results
     */
    relevancyStrictness?: number;
}

export interface VirtualIndexTimeouts {
    default?: string;
}

export interface VirtualIndexTyposConfig {
    /**
     * Whether to allow typos on numbers (“numeric tokens”) in the query str
     */
    allowTyposOnNumericTokens?: boolean;
    /**
     * List of attributes on which you want to disable typo tolerance.
     */
    disableTypoToleranceOnAttributes: string[];
    /**
     * List of words on which typo tolerance will be disabled.
     */
    disableTypoToleranceOnWords: string[];
    /**
     * Minimum number of characters a word in the query string must contain to accept matches with 1 typo.
     */
    minWordSizeFor1Typo?: number;
    /**
     * Minimum number of characters a word in the query string must contain to accept matches with 2 typos.
     */
    minWordSizeFor2Typos?: number;
    /**
     * Separators (punctuation characters) to index. By default, separators are not indexed.
     */
    separatorsToIndex?: string;
    /**
     * Whether typo tolerance is enabled and how it is applied
     */
    typoTolerance?: string;
}

