name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node, cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - id: auth
        name: Setup GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID_DEV }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: github-actions-sa@${{ vars.GCP_PROJECT_ID_DEV }}.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Set up Gcloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 416.0.0'
          project_id: ${{ vars.GCP_PROJECT_ID_DEV }}
          credentials_file_path: ${{ steps.auth.outputs.credentials_file_path }}

      - name: Print WIF inputs
        run: |
          echo "project_id=${{ vars.GCP_PROJECT_ID_DEV }}"
          echo "provider=${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}"
          echo "service_account=${{ vars.WORKLOAD_SERVICE_ACCOUNT_ID_DEV }}"

      - name: Show project info
        run: |
          gcloud auth list
          gcloud config list project
          gcloud projects describe ${{ vars.GCP_PROJECT_ID_DEV }}

      - run: npm ci

      - run: npx nx run-many -t lint

      - run: npx nx run-many -t deploy --configuration=dev --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
