name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID_DEV }}
          workload_identity_provider: ${{ vars.OIDC_PROVIDER_NAME_DEV }}
          service_account: ${{ vars.OIDC_SERVICE_ACCOUNT_DEV }}

      - name: Set up Gcloud
        uses: google-github-actions/setup-gcloud@v2

      - run: npm ci

      - run: npx nx run-many -t lint

      - run: npx nx run-many -t preview --configuration=dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
